image: node:12.16.3
clone:
  depth: full
pipelines:
   branches:
     staging:
       - step:
           caches:
             - node
           script:
             - yarn install
             - yarn run build
             - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
